# These are supported funding model platforms

Paypal: ![https://64.media.tumblr.com/b244e26528a0d9671ae328fcbc0e7f3d/2defa6b6c608cf47-13/s250x400/ec3e140414297a43db1f71024fba549c0ce8233a.png](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=JQ9BXNQUQS5NQ&currency_code=USD
)

