# These are supported funding model platforms

github: # Techy-Mature
ko_fi: # Replace with a single Ko-fi username
Paypal Donate: # https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=JQ9BXNQUQS5NQ&currency_code=USD
